# Generated by Django 6.0.6 on 2026-07-10 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postino', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGapOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=500)),
                ('volume', models.IntegerField(blank=True, help_text='Average monthly searches', null=True)),
                ('competition', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='UNKNOWN', max_length=10)),
                ('cpc_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cpc_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seed_keyword', models.CharField(blank=True, max_length=500)),
                ('suggested_slug', models.CharField(blank=True, max_length=255)),
                ('content_angle', models.TextField(blank=True)),
                ('source_report', models.CharField(blank=True, help_text='Report file that originated this record', max_length=500)),
                ('suggested_title', models.CharField(blank=True, max_length=200)),
                ('suggested_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('suggested', 'Suggested'), ('generated', 'Generated'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Gap Opportunity',
                'verbose_name_plural': 'Content Gap Opportunities',
                'ordering': ['-volume', 'keyword'],
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Blog Author Profile', 'verbose_name_plural': 'Blog Author Profiles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Blog Tag', 'verbose_name_plural': 'Blog Tags'},
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='postino_pos_status_2165bf_idx',
            old_name='postino_post_status_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='postino_pos_slug_a3f208_idx',
            old_name='postino_post_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='postino_pos_categor_ae226d_idx',
            old_name='postino_post_category_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='primary', help_text='Bootstrap color (primary, secondary, success, danger, warning, info)', max_length=20, verbose_name='Badge Color'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postino_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='postino.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(max_length=300, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/featured/%Y/%m/%d/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(default=5, verbose_name='Reading Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tag Name'),
        ),
        migrations.AddField(
            model_name='contentgapopportunity',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_gap_opportunities', to='postino.post'),
        ),
        migrations.AlterUniqueTogether(
            name='contentgapopportunity',
            unique_together={('keyword', 'source_report')},
        ),
    ]
