# Generated by Django 6.0.6 on 2026-07-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postino', '0002_content_gap_opportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='BCP 47 tag, e.g. en, pt-br, fr', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Display name, e.g. English', max_length=100)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(default='en', help_text="BCP 47 language code of this post's content, e.g. en, pt-br, fr", max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='post',
            name='translated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='postino.post', verbose_name='Translated from'),
        ),
        migrations.AddField(
            model_name='contentgapopportunity',
            name='target_languages',
            field=models.ManyToManyField(blank=True, help_text='Languages the generated post should be translated into.', related_name='opportunities', to='postino.language', verbose_name='Target translation languages'),
        ),
    ]
